version: "3.5"
networks:
  cleancontrol_network:
    driver: bridge
volumes:
  cleancontrol_volume:
services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=control
      - POSTGRES_USER=cleancontrol
      - POSTGRES_DB=cleancontrol
    volumes:
      - cleancontrol_volume:/var/lib/postgresql/data
    networks:
      - cleancontrol_network
    ports:
      - 5432:5432
